### ISSUE TITLE
current viewer - wrong body (from external)

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/PlanetaryNomenclature#23]
I'm thinking about expanding USGS's base of planetary nomenclature data to a 'name-to-position' interface: user gives the name of the crater, for instance, to get back its (central) position. And from the links in 'https://astrocloud.wr.usgs.gov/dataset/docs/index.html' I could find all the data I need to do it. Awesome, by the way. But at some point, in the "Nomenclature Summary" https://astrocloud.wr.usgs.gov/dataset/data/nomenclature/summary) I found some inconsistent info that I think is being caused by a bug somewhere in your system.

For example, the json at `https://astrocloud.wr.usgs.gov/dataset/data/nomenclature/summary` has an entry for Ganymede/Jupiter features -- which is itself a list of items containing links to `https://planetarynames.wr.usgs.gov/`. The last item of this list should link to a Ganymede craters I suppose, but instead it links to Oberon craters (https://planetarynames.wr.usgs.gov/SearchResults?target=OBERON&featureType=Crater,%20craters).

Is it a bug in the data or I got it wrong?

**Comment by thareUSGS** [comment]
from same external user:

I have two other issues to report -- as related to the 'NOMENCLATURE' data base previously posted about. The following bugs are in the WMS feature collections provided in https://astrocloud.wr.usgs.gov/dataset/data:
• one is related to encoding used for some features -- in the CALLISTO features collection, for example, there is this entry '\u00c4gr...';
• the second is about coordinates in wrong values, I found in the MOON and IO collections entries with longitude greater than 360.

**Comment by chbrandt** [comment]
Thanks @thareUSGS for bringing this here.

To clarify, there are three issues (or information that I didn't understand) above that I brought to the attention of Trent regarding USGS's Nomenclature data base. Summarizing them:
- [ ] Wrong association of `target` in URLs to table's _target_ index (_i.e._, objects don't match) ([1](https://github.com/USGS-Astrogeology/PlanetaryNomenclature/issues/23#issue-464717868));
- [ ] In the WMS services associated to the Nomenclature data base, some features go present coordinates beyond [0:360] limits. Maybe because those features effectively cross the 0/360 line, or maybe they are a bug ([2](https://github.com/USGS-Astrogeology/PlanetaryNomenclature/issues/23#issuecomment-511475465));
- [ ] I understand there are special characters in the data and they are represented in unicode, but it is not clear to me which encoding was used (utf8, iso-8859, ?)  ([2](https://github.com/USGS-Astrogeology/PlanetaryNomenclature/issues/23#issuecomment-511475465)).
